name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      working-directory: AZ/tf

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Instal AZ cli
    - name: az cli install
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      working-directory: AZ/tf
     

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend-config=backends/backend.hcl
      working-directory: AZ/tf
      env:
        ARM_CLIENT_ID : ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET : ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID : ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID : ${{ secrets.ARM_TENANT_ID }}  


    # Generate auto tfvars
    - name: Generate auto tfvars
      run: |
          echo -e "environment=$AZ_ENV \n" > .auto.tfvars
          echo -e "application_name=$APPLICATION_NAME \n" >> .auto.tfvars
          echo -e "business_unit=$BUSINESS_UNIT \n" >> .auto.tfvars
          echo -e "administrator_login_uid=$ADMINISTRATOR_LOG_ID \n" >> .auto.tfvars
          echo -e "administrator_login_pwd=$ADMINISTRATOR_LOGIN_PWD \n" >> .auto.tfvars
          echo -e "start_ip_address=$START_IP_ADDRESS \n" >> .auto.tfvars
          echo -e "end_ip_address=$END_IP_ADDRESS \n" >> .auto.tfvars
          echo -e "dr_regions=$DR_REGIONS" >> .auto.tfvars
          cat .auto.tfvars
      working-directory : AZ/tf
      env:
        ARM_CLIENT_ID : ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET : ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID : ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID : ${{ secrets.ARM_TENANT_ID }} 
        AZ_ENV : "dev"
        APPLICATION_NAME : "invoicecloud"
        BUSINESS_UNIT : "Payments"
        ADMINISTRATOR_LOG_ID : "sqladmin"
        ADMINISTRATOR_LOGIN_PWD : "P@$$.1w0rd"
        START_IP_ADDRESS : "107.206.241.87"
        END_IP_ADDRESS : "107.206.241.87"
        DR_REGIONS : "{ \
            pri = \"East US 2\" \
            sec = \"Central US\" \
        }"            

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: |
              terraform plan 
              echo  -e  "environment=$AZ_ENV \n \
application_name=$APPLICATION_NAME \n \
business_unit=$BUSINESS_UNIT \n \
administrator_login_uid=$ADMINISTRATOR_LOG_ID \n \
administrator_login_pwd=$ADMINISTRATOR_LOGIN_PWD \n \
start_ip_address=$START_IP_ADDRESS \n \
end_ip_address=$END_IP_ADDRESS \n \
dr_regions=$DR_REGIONS" > .auto.tfvars
              cat .auto.tfvars
      working-directory : AZ/tf
      env:
        ARM_CLIENT_ID : ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET : ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID : ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID : ${{ secrets.ARM_TENANT_ID }} 
        AZ_ENV : "dev"
        APPLICATION_NAME : "invoicecloud"
        BUSINESS_UNIT : "Payments"
        ADMINISTRATOR_LOG_ID : "sqladmin"
        ADMINISTRATOR_LOGIN_PWD : "P@$$.1w0rd"
        START_IP_ADDRESS : "107.206.241.87"
        END_IP_ADDRESS : "107.206.241.87"
        DR_REGIONS : "{ \
            pri = \"East US 2\" \
            sec = \"Central US\" \
        }"

      # On push to master, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: AZ/tf
      env:
        ARM_CLIENT_ID : ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET : ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID : ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID : ${{ secrets.ARM_TENANT_ID }}         
